build_package: Remove trailing comma for clone_scp_tools
'scmi_lib_commit' parameter being searched to find the correct
commit to checkout from the repo was originally laid out without
a comma.

Recent changes in the way that those parameters have been reworked
have led to append a comma.
Such comma is also grep'ed and that means that 'sha' becomes 'sha,'.

When checking out from "sha," git refuses with:

error: pathspec 'sha,' did not match any file(s) known to git

Fix the syntax for grep & tr in order to remove the trailing
comma to form the correct sha for checkout.

Signed-off-by: Nicola Mazzucato <nicola.mazzucato@arm.com>
Change-Id: I46dc92414f3ca14ce7e01e64c6987ff5d9c1e850